apiVersion: apps/v1 # API version being used
kind: Deployment # Type of Kubernetes object
metadata:
  name: webapp-deployment # Name of the deployment
  labels:
    app: webapp # Label to identify the app
spec:
  replicas: 1 # Number of pod replicas
  selector:
    matchLabels:
      app: webapp # Label selector to identify the pods
  template:
    metadata:
      labels:
        app: webapp # Label to identify the app
    spec:
      containers:
        - name: webapp # Name of the container
          image: docker-image # this name will be replaced in each push to the repository so that the latest image is always used
          ports:
            - containerPort: 3000 # Port to expose on the container
          resources:
            requests:
              cpu: 250m     # Minimum guaranteed CPU allocation (1/4 core)
              memory: 256Mi # Minimum guaranteed memory allocation
            limits:
              cpu: 500m     # Maximum CPU usage allowed (1/2 core)
              memory: 512Mi # Maximum memory usage allowed
      # This specifies the secret to be used for pulling the Docker image from the private registry
      imagePullSecrets:
        - name: ionossecretasad

---

apiVersion: v1 # API version being used
kind: Service # Type of Kubernetes object
metadata:
  name: webapp-service # Name of the service
spec:
  type: NodePort
  selector:
    app: webapp # Label selector to identify the pods
  ports:
    - protocol: TCP # Protocol to be used
      port: 3000 # Port to expose on the service
      targetPort: 3000 # Port to target on the pod
      nodePort: 30001 # Node port to expose on the service
