apiVersion: batch/v1
kind: Job
metadata:
  name: debug-job-with-busybox
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      containers:
      - name: debug-container-busybox
        image: busybox:latest
        command: ["sh", "-c", "sleep 3600"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
      restartPolicy: Never
  backoffLimit: 2
