name: Build Image

on: [push, pull_request]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build docker image
        run: docker build -t ${{ github.repository }}:latest .