name: Deploy to Minikube

on:
    push:
      branches:
        - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Start Minikube
          run: |
            minikube start --driver=docker
            minikube kubectl -- get pods --all-namespaces

        - name: Build & push Docker image
          uses: mr-smithers-excellent/docker-build-push@v6
          with:
            image: asad199/ci-cd-actions
            tags: ${{ github.sha }}, latest
            registry: docker.io
            dockerfile: Dockerfile
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Deploy to Minikube
          run: |
            kubectl apply -f web-app.yaml
            kubectl rollout status deployment/webapp-deployment

        - name: Get services
          run: kubectl get services
