# Name of the GitHub Action workflow
name: Deploy to IONOS

# Trigger the workflow on push events to the main branch
on:
    push:
      branches:
        - main

    workflow_dispatch:  # The 'workflow_dispatch' event allows you to manually trigger the workflow from the GitHub Actions tab without needing of push or pull request.

# Define the jobs to be run in the workflow
jobs:
  deploy:
    # Specify the runner environment
    runs-on: ubuntu-latest

    # Define the steps to be executed in the job
    steps:
        # Step to checkout the repository
        - name: Checkout repository
          uses: actions/checkout@v3

        # Step to build and push Docker image
        - name: Build & push Docker image
          uses: mr-smithers-excellent/docker-build-push@v6
          with:
            # Docker image name
            image: asad199/ci-cd-actions
            # Tags for the Docker image
            tags: ${{ github.sha }}, latest
            # Docker registry to push the image to
            registry: docker.io
            # Dockerfile to use for building the image
            dockerfile: Dockerfile
            # DockerHub username from secrets
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            # DockerHub token from secrets
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        # Step to create deployment to IONOS Kubernetes
        - name: Create deployment to IONOS Kubernetes
          uses: actions-hub/kubectl@master
          env:
            # Kubernetes configuration from secrets
            KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_IONOS }}
          with:
            # Arguments to apply the Kubernetes configuration file
            # The configuration file (web-app.yaml) includes:
            # - Deployment: Manages the deployment of the web app
            # - Service: Exposes the web app to the network
            args: apply -f web-app.yaml
