# Name of the GitHub Action workflow
name: Deploy to IONOS

# Trigger the workflow on push events to the main branch
on:
    push:
      branches:
        - main

    workflow_dispatch:  # The 'workflow_dispatch' event allows you to manually trigger the workflow from the GitHub Actions tab without needing of push or pull request.

# Define the jobs to be run in the workflow
jobs:
  deploy:
    # Specify the runner environment
    runs-on: ubuntu-latest

    # Define the steps to be executed in the job
    steps:
        # Step to checkout the repository
        - name: Checkout repository
          uses: actions/checkout@v3

        # Step to build and push Docker image
        - name: Build & push Docker image # This step builds and pushes the Docker image
          uses: mr-smithers-excellent/docker-build-push@v6
          with:
            image: asad199/ci-cd-actions # The name of the Docker image
            tags: ${{ github.sha }}, latest # Tags for the Docker image
            registry: ivicosregistry.cr.de-fra.ionos.com # The Docker registry to push the image to
            dockerfile: Dockerfile # The Dockerfile to use for building the image
            username: ${{ secrets.IONOS_TOKEN_NAME }} # IONOS token name from secrets
            password: ${{ secrets.IONOS_TOKEN_PASSWORD }} # IONOS token password from secrets

        - name: Replace docker-image name in web-app.yaml
            # Use the 'sed' command to find and replace the Docker image name in the web-app.yaml file
            # 'sed -i' is used to edit the file in place
            # 's|image: docker-image|image: asad199/ci-cd-actions:${{ github.sha }}|g' is the substitution pattern
            # It replaces 'image: docker-image' with 'image: asad199/ci-cd-actions:${{ github.sha }}' globally in the file
          run: |
            sed -i 's|image: docker-image|image: ivicosregistry.cr.de-fra.ionos.com/asad199/ci-cd-actions:${{ github.sha }}|g' web-app.yaml

        # Step to create deployment to IONOS Kubernetes
        - name: Create deployment to IONOS Kubernetes
          uses: actions-hub/kubectl@master
          env:
            # Kubernetes configuration from secrets
            KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_IONOS }}
          with:
            # Arguments to apply the Kubernetes configuration file
            # The configuration file (web-app.yaml) includes:
            # - Deployment: Manages the deployment of the web app
            # - Service: Exposes the web app to the network
            args: apply -f web-app.yaml
